# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-30 17:59
from __future__ import unicode_literals

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [("server", "0014_migrate_secrets")]

    operations = [
        migrations.RemoveField(model_name="secret", name="secret"),
        migrations.RenameField(
            model_name="secret", old_name="new_secret", new_name="secret"
        ),
    ]
